//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crudapp.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_Student
    {
        public int ID { get; set; }

        [Required(ErrorMessage ="Required")]
        public string Name { get; set; }

        [Required(ErrorMessage = "REQUIRED!!")]
        public string Fname { get; set; }

        [Required(ErrorMessage = "REQUIRED!!")]
        [EmailAddress]
        public string Email { get; set; }

        [Required(ErrorMessage = "REQUIRED!!")]
        [MinLength(10,ErrorMessage ="Not Valid")]
        public string Mobile { get; set; }
        public string Description { get; set; }
    }
}
